FROM (base-image)

WORKDIR <directory>

COPY package.json /app/

COPY . .

RUN <command_name>

EXPOSE 9000
  
RUN npm install

CMD ["executable","param1","param2",...]   

#run this command to create docker image 
docker build -t <image_name> . 
